version: "3.8"
services:
  atm-server:
    build: atm-service
    restart: always
    ports:
      - 8082:8082
    depends_on:
      - bank-server
  bank-server:
    build: bank-service
    restart: always
    ports:
      - 8081:8081
    depends_on:
       - mysqldb
  mysqldb:
    image : mysql
    restart: always
    ports :
      - 3307:3306
    environment:
       MYSQL_DATABASE: bankdb
       MYSQL_USER: sa
       MYSQL_PASSWORD: 123456
       MYSQL_ROOT_PASSWORD: 123456





