

spring:
  profiles:
    active : dev
---
spring:
  profiles: dev
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/test
    password:
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
---
spring:
  profiles: prod
  datasource:
    username: sa
    url: jdbc:mysql://mysqldb:3306/bankdb
    password: 123456
  jpa:
    show-sql: 'false'
    hibernate:
      ddl-auto: none


